language: rust
sudo: required
dist: trusty
addons:
  apt:
    packages:
      - libssl-dev

rust:
  - nightly
  - beta
  - stable

cache: cargo

env:
  - CARGO_FEATURES=""
  - CARGO_FEATURES="no-simd"

matrix:
  allow_failures:
    - rust: nightly

before_cache: |
  if [[ "$TRAVIS_RUST_VERSION" == nightly ]]; then
    RUSTFLAGS="--cfg procmacro2_semver_exempt" cargo install cargo-tarpaulin -f
  fi

script:
  - cargo clean
  - cargo build --features "$CARGO_FEATURES"
  - cargo test --features "$CARGO_FEATURES"

after_success: |
  if [[ "$TRAVIS_RUST_VERSION" == nightly ]]; then
    cargo tarpaulin --features no-simd --exclude-files src/fast_f32/mod.rs --exclude-files src/f32/vec3_f32x4.rs --exclude-files src/f32/vec4_f32x4.rs --ciserver travis-ci --coveralls $TRAVIS_JOB_ID
    cargo tarpaulin --exclude-files src/fast_f32/mod.rs --exclude-files src/f32/vec3_f32.rs --exclude-files src/f32/vec4_f32.rs --ciserver travis-ci --coveralls $TRAVIS_JOB_ID

    # Uncomment the following two lines create and upload a report for codecov.io
    # cargo tarpaulin --out Xml
    # bash <(curl -s https://codecov.io/bash)
  fi
