[package]
name = "glam"
version = "0.1.0"
authors = ["Cameron Hart <cameron.hart@gmail.com>"]
edition = "2018"

[features]
default = ["approx", "rand", "serde"]

# this is primarily for testing the fallback implementation
no-simd = []

# trying out transform types instead of matrices but they are generally slower
# at everything except for inverse. They are 16 bytes smaller than a Mat4.
transform-types = []

[dependencies]
# TODO: make this dev only
approx = { version = "0.3", optional = true }
rand = { version = "0.6", optional = true }
serde = { version = "1.0", optional = true, features = ["derive"] }

[dev-dependencies]
approx = "0.3"
criterion = "0.2"
rand_xoshiro = "0.1"
serde_json = "1.0"

[[bench]]
name = "mat4"
harness = false
required-features = ["transform-types"]

[[bench]]
name = "quat"
harness = false

[[bench]]
name = "transform"
harness = false
required-features = ["transform-types"]

[[bench]]
name = "vec3"
harness = false
required-features = ["transform-types"]
