[package]
name = "glam"
version = "0.1.0"
authors = ["Cameron Hart <cameron.hart@gmail.com>"]
edition = "2018"

[features]
default = ["approx", "rand", "serde"]

# this is primarily for testing the fallback implementation
no-simd = []

[dependencies]
# TODO: make this dev only
approx = { version = "0.3", optional = true }
rand = { version = "0.6", optional = true }
serde = { version = "1.0", optional = true, features = ["derive"] }

[dev-dependencies]
approx = "0.3"
criterion = "0.2"
rand_xoshiro = "0.1"
serde_json = "1.0"

[[bench]]
name = "mat4"
harness = false
