name: CI
on: [push, pull_request]
jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu, macos, windows]
        rust: [1.36.0, stable, beta, nightly]
    runs-on: ${{ matrix.os }}-latest
    steps:
      - uses: actions/checkout@v2
      - run: rustup default ${{ matrix.rust }}
      - run: cargo build --no-default-features --features libm
      - run: cargo build
      - run: ./build_and_test_features.sh
        shell: bash

